-- DROP database if exists ryldb;
-- create database ryldb;
-- use ryldb;
-- create table users (
-- id int auto_increment PRIMARY KEY, 
-- username varchar(30),
-- `password` varchar(500)
-- )
-- create table reviews (
-- id int auto_increment PRIMARY KEY, 
-- `name` varchar(30),
-- `address` varchar(60),
-- website varchar(500),
-- rating int,
-- rentAgain boolean,
-- review varchar(500),
-- images varchar(50)
-- );
